// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package ZMDev_Noxus_pb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	AppValidateRes
	AppCredential
	AppID
	Application
	AppListReq
	AppList
*/
package ZMDev_Noxus_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppValidateRes struct {
	IsValid bool `protobuf:"varint,1,opt,name=isValid" json:"isValid,omitempty"`
}

func (m *AppValidateRes) Reset()                    { *m = AppValidateRes{} }
func (m *AppValidateRes) String() string            { return proto.CompactTextString(m) }
func (*AppValidateRes) ProtoMessage()               {}
func (*AppValidateRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppValidateRes) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type AppCredential struct {
	Id     int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (m *AppCredential) Reset()                    { *m = AppCredential{} }
func (m *AppCredential) String() string            { return proto.CompactTextString(m) }
func (*AppCredential) ProtoMessage()               {}
func (*AppCredential) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppCredential) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppCredential) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type AppID struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *AppID) Reset()                    { *m = AppID{} }
func (m *AppID) String() string            { return proto.CompactTextString(m) }
func (*AppID) ProtoMessage()               {}
func (*AppID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Application struct {
	Id          int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LogoHash    string `protobuf:"bytes,2,opt,name=logo_hash,json=logoHash" json:"logo_hash,omitempty"`
	UserId      int64  `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Url         string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Name        string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Revoked     bool   `protobuf:"varint,7,opt,name=revoked" json:"revoked,omitempty"`
	CreatedAt   int64  `protobuf:"varint,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   int64  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	DeletedAt   int64  `protobuf:"varint,10,opt,name=deleted_at,json=deletedAt" json:"deleted_at,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Application) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Application) GetLogoHash() string {
	if m != nil {
		return m.LogoHash
	}
	return ""
}

func (m *Application) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Application) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Application) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Application) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Application) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type AppListReq struct {
	PerPage int32 `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	Page    int32 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
}

func (m *AppListReq) Reset()                    { *m = AppListReq{} }
func (m *AppListReq) String() string            { return proto.CompactTextString(m) }
func (*AppListReq) ProtoMessage()               {}
func (*AppListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AppListReq) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *AppListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type AppList struct {
	Apps []*Application `protobuf:"bytes,1,rep,name=apps" json:"apps,omitempty"`
}

func (m *AppList) Reset()                    { *m = AppList{} }
func (m *AppList) String() string            { return proto.CompactTextString(m) }
func (*AppList) ProtoMessage()               {}
func (*AppList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AppList) GetApps() []*Application {
	if m != nil {
		return m.Apps
	}
	return nil
}

func init() {
	proto.RegisterType((*AppValidateRes)(nil), "ZMDev.Noxus.pb.AppValidateRes")
	proto.RegisterType((*AppCredential)(nil), "ZMDev.Noxus.pb.AppCredential")
	proto.RegisterType((*AppID)(nil), "ZMDev.Noxus.pb.AppID")
	proto.RegisterType((*Application)(nil), "ZMDev.Noxus.pb.Application")
	proto.RegisterType((*AppListReq)(nil), "ZMDev.Noxus.pb.AppListReq")
	proto.RegisterType((*AppList)(nil), "ZMDev.Noxus.pb.AppList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AppService service

type AppServiceClient interface {
	Validate(ctx context.Context, in *AppCredential, opts ...grpc.CallOption) (*AppValidateRes, error)
	Find(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*Application, error)
	List(ctx context.Context, in *AppListReq, opts ...grpc.CallOption) (*AppList, error)
}

type appServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppServiceClient(cc *grpc.ClientConn) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) Validate(ctx context.Context, in *AppCredential, opts ...grpc.CallOption) (*AppValidateRes, error) {
	out := new(AppValidateRes)
	err := grpc.Invoke(ctx, "/ZMDev.Noxus.pb.AppService/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) Find(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/ZMDev.Noxus.pb.AppService/Find", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) List(ctx context.Context, in *AppListReq, opts ...grpc.CallOption) (*AppList, error) {
	out := new(AppList)
	err := grpc.Invoke(ctx, "/ZMDev.Noxus.pb.AppService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppService service

type AppServiceServer interface {
	Validate(context.Context, *AppCredential) (*AppValidateRes, error)
	Find(context.Context, *AppID) (*Application, error)
	List(context.Context, *AppListReq) (*AppList, error)
}

func RegisterAppServiceServer(s *grpc.Server, srv AppServiceServer) {
	s.RegisterService(&_AppService_serviceDesc, srv)
}

func _AppService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCredential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZMDev.Noxus.pb.AppService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).Validate(ctx, req.(*AppCredential))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZMDev.Noxus.pb.AppService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).Find(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZMDev.Noxus.pb.AppService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).List(ctx, req.(*AppListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ZMDev.Noxus.pb.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _AppService_Validate_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _AppService_Find_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AppService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x6f, 0x9a, 0xb4, 0x49, 0x4e, 0xb1, 0xc8, 0x80, 0x76, 0xec, 0xe5, 0x4a, 0x98, 0x55,
	0x71, 0x11, 0xe1, 0xba, 0x10, 0xfc, 0xb3, 0x08, 0x16, 0xb1, 0xf8, 0x07, 0x89, 0xe0, 0xc2, 0x4d,
	0x99, 0x9b, 0x39, 0xb4, 0x83, 0xb1, 0x39, 0xce, 0x4c, 0x8b, 0xcf, 0xe1, 0xc3, 0xf9, 0x3c, 0x92,
	0xe9, 0x14, 0xab, 0x56, 0x77, 0x73, 0xbe, 0xdf, 0x77, 0xe6, 0x64, 0xbe, 0x1c, 0xc8, 0x25, 0xe9,
	0x92, 0x4c, 0xe7, 0x3a, 0x36, 0xf9, 0xf4, 0x76, 0x81, 0xfb, 0xf2, 0x5d, 0xf7, 0x6d, 0x67, 0x4b,
	0xba, 0x11, 0x0f, 0x60, 0x52, 0x11, 0x7d, 0x94, 0xad, 0x56, 0xd2, 0x61, 0x8d, 0x96, 0x71, 0x48,
	0xb5, 0xf5, 0x02, 0x8f, 0x8a, 0x68, 0x9e, 0xd5, 0xc7, 0x52, 0x3c, 0x86, 0x5b, 0x15, 0xd1, 0x0b,
	0x83, 0x0a, 0xb7, 0x4e, 0xcb, 0x96, 0x4d, 0x60, 0x10, 0x5c, 0xc3, 0x7a, 0xa0, 0x15, 0xbb, 0x0b,
	0x23, 0x8b, 0x8d, 0x41, 0xc7, 0x07, 0x45, 0x34, 0xcf, 0xeb, 0x50, 0x89, 0x29, 0x0c, 0x2b, 0xa2,
	0xe5, 0xe2, 0xcf, 0x06, 0xf1, 0x7d, 0x00, 0xe3, 0x8a, 0xa8, 0xd5, 0x8d, 0x74, 0xba, 0xdb, 0xfe,
	0x75, 0xe1, 0x25, 0xe4, 0x6d, 0xb7, 0xee, 0x56, 0x1b, 0x69, 0x37, 0xe1, 0xce, 0xac, 0x17, 0x5e,
	0x49, 0xbb, 0x61, 0x53, 0x48, 0x77, 0x16, 0xcd, 0x4a, 0x2b, 0x1e, 0x17, 0xd1, 0x3c, 0xae, 0x47,
	0x7d, 0xb9, 0x54, 0xec, 0x36, 0xc4, 0x3b, 0xd3, 0xf2, 0xc4, 0xfb, 0xfb, 0x23, 0x63, 0x90, 0x6c,
	0xe5, 0x17, 0xe4, 0x43, 0x2f, 0xf9, 0x33, 0x2b, 0x60, 0xac, 0xd0, 0x36, 0x46, 0x53, 0x3f, 0x9a,
	0x8f, 0x3c, 0x3a, 0x95, 0xfa, 0x24, 0x0c, 0xee, 0xbb, 0xcf, 0xa8, 0x78, 0x7a, 0x48, 0x22, 0x94,
	0xec, 0x0a, 0xa0, 0x31, 0x28, 0x1d, 0xaa, 0x95, 0x74, 0x3c, 0xf3, 0xd3, 0xf3, 0xa0, 0x54, 0xae,
	0xc7, 0x3b, 0x52, 0x47, 0x9c, 0x1f, 0x70, 0x50, 0x0e, 0x58, 0x61, 0x8b, 0x01, 0xc3, 0x01, 0x07,
	0xa5, 0x72, 0xe2, 0x29, 0x40, 0x45, 0xf4, 0x46, 0x5b, 0x57, 0xe3, 0x57, 0x76, 0x0f, 0x32, 0x42,
	0xb3, 0x22, 0xb9, 0x46, 0x9f, 0xc0, 0xb0, 0x4e, 0x09, 0xcd, 0x7b, 0xb9, 0xc6, 0xfe, 0x55, 0x5e,
	0x8e, 0xbd, 0xec, 0xcf, 0xe2, 0x09, 0xa4, 0xa1, 0x99, 0x3d, 0x84, 0x44, 0x12, 0x59, 0x1e, 0x15,
	0xf1, 0x7c, 0x7c, 0x7d, 0x59, 0xfe, 0xfe, 0xe7, 0xcb, 0x93, 0xdc, 0x6b, 0x6f, 0xbc, 0xfe, 0x11,
	0xf9, 0xc9, 0x1f, 0xd0, 0xec, 0x75, 0x83, 0xec, 0x35, 0x64, 0xc7, 0xbd, 0x60, 0x57, 0x67, 0xba,
	0x7f, 0x2d, 0xc2, 0xec, 0xfe, 0x19, 0x7c, 0xb2, 0x53, 0xe2, 0x82, 0x3d, 0x83, 0xe4, 0xa5, 0xde,
	0x2a, 0x76, 0xe7, 0x8c, 0x73, 0xb9, 0x98, 0xfd, 0xef, 0xeb, 0xc4, 0x05, 0x7b, 0x0e, 0x89, 0x7f,
	0xd2, 0xec, 0x8c, 0x2d, 0x04, 0x35, 0x9b, 0xfe, 0x83, 0x89, 0x8b, 0x9b, 0x91, 0xdf, 0xfd, 0x47,
	0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x67, 0x4d, 0x51, 0x17, 0x08, 0x03, 0x00, 0x00,
}
